//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cindice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion
    {
        public int CalificacionId { get; set; }
        public Nullable<int> EstudiantesId { get; set; }
        public Nullable<int> AsignaturaId { get; set; }
        public string Calificación { get; set; }
        public Nullable<int> Promedio { get; set; }
    
        public virtual Asignatura Asignatura { get; set; }
        public virtual Estudiantes Estudiantes { get; set; }
    }
}
